CREATE TABLE IF NOT EXISTS task_templates (
  id VARCHAR(255) PRIMARY KEY,
  template_key VARCHAR(255) NOT NULL,
  title VARCHAR(255) NOT NULL,
  subtitle VARCHAR(255) NOT NULL,
  grade VARCHAR(32) NOT NULL,
  age_group VARCHAR(64) NOT NULL,
  schedule_type VARCHAR(64) NOT NULL,
  day_type VARCHAR(64) NOT NULL,
  tags_json TEXT NOT NULL,
  status VARCHAR(64) NOT NULL DEFAULT 'active',
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at BIGINT NOT NULL,
  updated_at BIGINT NOT NULL,
  UNIQUE KEY uq_task_templates_template_key (template_key)
);

CREATE INDEX idx_task_templates_grade
  ON task_templates(grade, status, sort_order);

CREATE INDEX idx_task_templates_day_type
  ON task_templates(day_type, status, sort_order);

CREATE TABLE IF NOT EXISTS task_template_items (
  id VARCHAR(255) PRIMARY KEY,
  template_id VARCHAR(255) NOT NULL,
  start_time VARCHAR(16) NOT NULL,
  end_time VARCHAR(16) NOT NULL,
  task_type VARCHAR(64) NOT NULL,
  title VARCHAR(255) NOT NULL,
  reward_points INTEGER NOT NULL DEFAULT 0,
  requires_parent_confirmation TINYINT NOT NULL DEFAULT 0,
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at BIGINT NOT NULL,
  updated_at BIGINT NOT NULL,
  CONSTRAINT fk_task_template_items_template
    FOREIGN KEY (template_id) REFERENCES task_templates(id)
);

CREATE INDEX idx_task_template_items_template
  ON task_template_items(template_id, sort_order);

INSERT INTO task_templates(
  id, template_key, title, subtitle, grade, age_group, schedule_type,
  day_type, tags_json, status, sort_order, created_at, updated_at
) VALUES
  ('kg-small-school-morning', 'kg-small-school-morning', '上学日晨间', '起床、早餐和入园前的小准备', 'small', 'kindergarten_small', 'weekday', 'school_day', '["school_day","morning","self_care","meal"]', 'active', 101, 0, 0),
  ('kg-small-school-entry-calm', 'kg-small-school-entry-calm', '入园前安心', '出门前轻轻确认，减少分离焦虑', 'small', 'kindergarten_small', 'weekday', 'school_day', '["school_day","morning","emotion","self_care"]', 'active', 102, 0, 0),
  ('kg-small-after-school-buffer', 'kg-small-after-school-buffer', '放学后缓冲', '喝水、抱抱，再慢慢进入家里节奏', 'small', 'kindergarten_small', 'weekday', 'school_day', '["school_day","after_school","emotion","outdoor"]', 'active', 103, 0, 0),
  ('kg-small-dinner-slow', 'kg-small-dinner-slow', '晚餐慢慢吃', '洗手、坐好、慢慢吃', 'small', 'kindergarten_small', 'daily', 'school_day', '["school_day","meal","self_care"]', 'active', 104, 0, 0),
  ('kg-small-nap-rhythm', 'kg-small-nap-rhythm', '午睡前后', '睡前安静，醒后慢慢恢复', 'small', 'kindergarten_small', 'daily', 'school_day', '["school_day","bedtime","self_care"]', 'active', 105, 0, 0),
  ('kg-small-bedtime-light', 'kg-small-bedtime-light', '睡前轻节奏', '洗漱、绘本和安静上床', 'small', 'kindergarten_small', 'daily', 'school_day', '["school_day","bedtime","reading","self_care"]', 'active', 106, 0, 0),
  ('kg-small-toy-home', 'kg-small-toy-home', '玩具回位', '玩好以后，把玩具送回家', 'small', 'kindergarten_small', 'one_time', 'weekend', '["weekend","cleanup","self_care"]', 'active', 107, 0, 0),
  ('kg-small-weekend-outdoor', 'kg-small-weekend-outdoor', '周末上午户外', '出门走走，回来喝水休息', 'small', 'kindergarten_small', 'weekly', 'weekend', '["weekend","outdoor","meal"]', 'active', 108, 0, 0),
  ('kg-small-weekend-reading', 'kg-small-weekend-reading', '亲子绘本', '短一点，读完聊一句', 'small', 'kindergarten_small', 'weekly', 'weekend', '["weekend","reading","emotion"]', 'active', 109, 0, 0),
  ('kg-small-emotion-calm', 'kg-small-emotion-calm', '情绪安抚', '把不开心说出来，慢慢缓过来', 'small', 'kindergarten_small', 'one_time', 'weekend', '["weekend","emotion","reading"]', 'active', 110, 0, 0),
  ('kg-middle-school-morning', 'kg-middle-school-morning', '晨间自理', '自己完成几件小事', 'middle', 'kindergarten_middle', 'weekday', 'school_day', '["school_day","morning","self_care","meal"]', 'active', 201, 0, 0),
  ('kg-middle-after-school-talk', 'kg-middle-after-school-talk', '放学后表达', '聊聊今天，再动一动', 'middle', 'kindergarten_middle', 'weekday', 'school_day', '["school_day","after_school","emotion","outdoor"]', 'active', 202, 0, 0),
  ('kg-middle-meal-before-after', 'kg-middle-meal-before-after', '餐前餐后', '洗手、坐好、饭后收一收', 'middle', 'kindergarten_middle', 'daily', 'school_day', '["school_day","meal","cleanup"]', 'active', 203, 0, 0),
  ('kg-middle-toy-sort', 'kg-middle-toy-sort', '玩具分类收纳', '积木、车车和绘本各回各位', 'middle', 'kindergarten_middle', 'weekly', 'weekend', '["weekend","cleanup","self_care"]', 'active', 204, 0, 0),
  ('kg-middle-bedtime-ready', 'kg-middle-bedtime-ready', '睡前准备', '自己收尾，安静入睡', 'middle', 'kindergarten_middle', 'daily', 'school_day', '["school_day","bedtime","reading","self_care"]', 'active', 205, 0, 0),
  ('kg-middle-weekend-outdoor', 'kg-middle-weekend-outdoor', '周末户外', '跑跳、补水，再回来休息', 'middle', 'kindergarten_middle', 'weekly', 'weekend', '["weekend","outdoor","meal"]', 'active', 206, 0, 0),
  ('kg-middle-family-helper', 'kg-middle-family-helper', '家庭小帮手', '参与家里的小事，感受合作', 'middle', 'kindergarten_middle', 'weekly', 'weekend', '["weekend","helper","cleanup","meal"]', 'active', 207, 0, 0),
  ('kg-middle-rules-turns', 'kg-middle-rules-turns', '规则与轮流', '玩之前说好规则，也能等等别人', 'middle', 'kindergarten_middle', 'weekly', 'weekend', '["weekend","rules","emotion","outdoor"]', 'active', 208, 0, 0),
  ('kg-middle-emotion-words', 'kg-middle-emotion-words', '情绪表达', '用词说心情，不急着评判', 'middle', 'kindergarten_middle', 'one_time', 'school_day', '["school_day","emotion","reading"]', 'active', 209, 0, 0),
  ('kg-middle-weekend-reading', 'kg-middle-weekend-reading', '亲子阅读', '读完说一句喜欢的地方', 'middle', 'kindergarten_middle', 'weekly', 'weekend', '["weekend","reading","emotion"]', 'active', 210, 0, 0),
  ('kg-big-school-ready', 'kg-big-school-ready', '晨间自主准备', '自己准备好一天开始', 'big', 'kindergarten_big', 'weekday', 'school_day', '["school_day","morning","self_care","meal"]', 'active', 301, 0, 0),
  ('kg-big-after-school-review', 'kg-big-after-school-review', '放学后复盘', '说说今天，也留一点户外时间', 'big', 'kindergarten_big', 'weekday', 'school_day', '["school_day","after_school","emotion","outdoor"]', 'active', 302, 0, 0),
  ('kg-big-table-duty', 'kg-big-table-duty', '餐桌小责任', '自己准备，也帮家里一点点', 'big', 'kindergarten_big', 'daily', 'school_day', '["school_day","meal","helper","cleanup"]', 'active', 303, 0, 0),
  ('kg-big-bedtime-self', 'kg-big-bedtime-self', '睡前自主', '自己收尾，安静上床', 'big', 'kindergarten_big', 'daily', 'school_day', '["school_day","bedtime","reading","self_care"]', 'active', 304, 0, 0),
  ('kg-big-weekend-outdoor', 'kg-big-weekend-outdoor', '周末户外', '有规则地活动，结束后整理', 'big', 'kindergarten_big', 'weekly', 'weekend', '["weekend","outdoor","rules","cleanup"]', 'active', 305, 0, 0),
  ('kg-big-weekend-reading', 'kg-big-weekend-reading', '亲子阅读', '读完能复述一点，不要求认字', 'big', 'kindergarten_big', 'weekly', 'weekend', '["weekend","reading","emotion"]', 'active', 306, 0, 0),
  ('kg-big-family-helper', 'kg-big-family-helper', '家庭小帮手', '承担一点家里的小责任', 'big', 'kindergarten_big', 'weekly', 'weekend', '["weekend","helper","cleanup","meal"]', 'active', 307, 0, 0),
  ('kg-big-own-things', 'kg-big-own-things', '整理自己的物品', '衣物、图书和玩具各有位置', 'big', 'kindergarten_big', 'weekly', 'weekend', '["weekend","cleanup","self_care"]', 'active', 308, 0, 0),
  ('kg-big-life-prep', 'kg-big-life-prep', '生活准备', '练生活能力，不增加压力', 'big', 'kindergarten_big', 'weekday', 'school_day', '["school_day","self_care","rules","cleanup"]', 'active', 309, 0, 0),
  ('kg-big-safety-rules', 'kg-big-safety-rules', '安全与规则', '用简单规则保护自己', 'big', 'kindergarten_big', 'weekly', 'weekend', '["weekend","rules","outdoor","emotion"]', 'active', 310, 0, 0)
ON DUPLICATE KEY UPDATE
  title = VALUES(title),
  subtitle = VALUES(subtitle),
  grade = VALUES(grade),
  age_group = VALUES(age_group),
  schedule_type = VALUES(schedule_type),
  day_type = VALUES(day_type),
  tags_json = VALUES(tags_json),
  status = VALUES(status),
  sort_order = VALUES(sort_order),
  updated_at = VALUES(updated_at);

INSERT INTO task_template_items(
  id, template_id, start_time, end_time, task_type, title,
  reward_points, requires_parent_confirmation, sort_order, created_at, updated_at
) VALUES
  ('kg-small-school-morning-1', 'kg-small-school-morning', '07:15', '07:30', 'life', '穿衣洗漱', 1, 0, 1, 0, 0),
  ('kg-small-school-morning-2', 'kg-small-school-morning', '07:30', '07:50', 'checkin', '坐好吃早餐', 1, 0, 2, 0, 0),
  ('kg-small-school-morning-3', 'kg-small-school-morning', '07:50', '08:00', 'housework', '带好水杯', 1, 1, 3, 0, 0),
  ('kg-small-school-entry-calm-1', 'kg-small-school-entry-calm', '07:40', '07:50', 'life', '自己穿好鞋', 1, 0, 1, 0, 0),
  ('kg-small-school-entry-calm-2', 'kg-small-school-entry-calm', '07:50', '08:00', 'custom', '说一句今天想做的事', 0, 0, 2, 0, 0),
  ('kg-small-school-entry-calm-3', 'kg-small-school-entry-calm', '08:00', '08:08', 'custom', '出门前抱抱', 0, 0, 3, 0, 0),
  ('kg-small-after-school-buffer-1', 'kg-small-after-school-buffer', '17:20', '17:30', 'life', '喝水休息', 1, 0, 1, 0, 0),
  ('kg-small-after-school-buffer-2', 'kg-small-after-school-buffer', '17:35', '18:00', 'sports_outdoor', '户外走走', 2, 0, 2, 0, 0),
  ('kg-small-after-school-buffer-3', 'kg-small-after-school-buffer', '18:05', '18:15', 'housework', '玩具回到盒子', 1, 0, 3, 0, 0),
  ('kg-small-dinner-slow-1', 'kg-small-dinner-slow', '18:00', '18:10', 'life', '餐前洗手', 1, 0, 1, 0, 0),
  ('kg-small-dinner-slow-2', 'kg-small-dinner-slow', '18:10', '18:35', 'checkin', '坐好慢慢吃', 1, 0, 2, 0, 0),
  ('kg-small-dinner-slow-3', 'kg-small-dinner-slow', '18:40', '18:50', 'housework', '餐具放回去', 1, 0, 3, 0, 0),
  ('kg-small-nap-rhythm-1', 'kg-small-nap-rhythm', '12:40', '12:50', 'life', '睡前上厕所', 1, 0, 1, 0, 0),
  ('kg-small-nap-rhythm-2', 'kg-small-nap-rhythm', '12:50', '13:10', 'sleep', '安静躺好', 1, 0, 2, 0, 0),
  ('kg-small-nap-rhythm-3', 'kg-small-nap-rhythm', '15:00', '15:10', 'life', '醒后喝水', 1, 0, 3, 0, 0),
  ('kg-small-bedtime-light-1', 'kg-small-bedtime-light', '20:15', '20:30', 'sleep', '洗漱准备', 1, 0, 1, 0, 0),
  ('kg-small-bedtime-light-2', 'kg-small-bedtime-light', '20:30', '20:45', 'reading_interest', '听一个故事', 1, 0, 2, 0, 0),
  ('kg-small-bedtime-light-3', 'kg-small-bedtime-light', '20:45', '21:00', 'sleep', '躺好休息', 1, 0, 3, 0, 0),
  ('kg-small-toy-home-1', 'kg-small-toy-home', '16:20', '16:30', 'housework', '积木放回盒子', 1, 0, 1, 0, 0),
  ('kg-small-toy-home-2', 'kg-small-toy-home', '16:30', '16:40', 'housework', '绘本放回书架', 1, 0, 2, 0, 0),
  ('kg-small-toy-home-3', 'kg-small-toy-home', '16:40', '16:50', 'custom', '看看地面干净了吗', 1, 1, 3, 0, 0),
  ('kg-small-weekend-outdoor-1', 'kg-small-weekend-outdoor', '09:20', '09:50', 'sports_outdoor', '户外散步', 2, 0, 1, 0, 0),
  ('kg-small-weekend-outdoor-2', 'kg-small-weekend-outdoor', '10:00', '10:15', 'checkin', '点心和喝水', 1, 0, 2, 0, 0),
  ('kg-small-weekend-outdoor-3', 'kg-small-weekend-outdoor', '10:45', '10:55', 'housework', '玩具回位', 1, 0, 3, 0, 0),
  ('kg-small-weekend-reading-1', 'kg-small-weekend-reading', '10:00', '10:15', 'reading_interest', '亲子绘本', 1, 0, 1, 0, 0),
  ('kg-small-weekend-reading-2', 'kg-small-weekend-reading', '10:15', '10:25', 'custom', '说说喜欢哪一页', 0, 0, 2, 0, 0),
  ('kg-small-weekend-reading-3', 'kg-small-weekend-reading', '10:25', '10:35', 'housework', '书放回书架', 1, 0, 3, 0, 0),
  ('kg-small-emotion-calm-1', 'kg-small-emotion-calm', '17:20', '17:30', 'custom', '说说今天心情', 0, 0, 1, 0, 0),
  ('kg-small-emotion-calm-2', 'kg-small-emotion-calm', '17:30', '17:45', 'reading_interest', '读一本喜欢的书', 1, 0, 2, 0, 0),
  ('kg-small-emotion-calm-3', 'kg-small-emotion-calm', '17:45', '18:00', 'sports_outdoor', '走走放松', 1, 0, 3, 0, 0),
  ('kg-middle-school-morning-1', 'kg-middle-school-morning', '07:10', '07:25', 'life', '自己穿衣', 1, 0, 1, 0, 0),
  ('kg-middle-school-morning-2', 'kg-middle-school-morning', '07:30', '07:50', 'checkin', '安静吃早餐', 1, 0, 2, 0, 0),
  ('kg-middle-school-morning-3', 'kg-middle-school-morning', '07:55', '08:05', 'housework', '检查水杯', 1, 1, 3, 0, 0),
  ('kg-middle-after-school-talk-1', 'kg-middle-after-school-talk', '17:20', '17:35', 'custom', '聊聊今天', 1, 0, 1, 0, 0),
  ('kg-middle-after-school-talk-2', 'kg-middle-after-school-talk', '17:40', '18:10', 'sports_outdoor', '户外跑跳', 2, 0, 2, 0, 0),
  ('kg-middle-after-school-talk-3', 'kg-middle-after-school-talk', '18:10', '18:20', 'housework', '收好玩具', 1, 0, 3, 0, 0),
  ('kg-middle-meal-before-after-1', 'kg-middle-meal-before-after', '17:55', '18:05', 'life', '餐前洗手', 1, 0, 1, 0, 0),
  ('kg-middle-meal-before-after-2', 'kg-middle-meal-before-after', '18:05', '18:30', 'checkin', '坐好吃饭', 1, 0, 2, 0, 0),
  ('kg-middle-meal-before-after-3', 'kg-middle-meal-before-after', '18:35', '18:45', 'housework', '收好餐垫', 1, 0, 3, 0, 0),
  ('kg-middle-toy-sort-1', 'kg-middle-toy-sort', '16:20', '16:30', 'housework', '积木放回盒子', 1, 0, 1, 0, 0),
  ('kg-middle-toy-sort-2', 'kg-middle-toy-sort', '16:30', '16:40', 'housework', '绘本放回书架', 1, 0, 2, 0, 0),
  ('kg-middle-toy-sort-3', 'kg-middle-toy-sort', '16:40', '16:50', 'custom', '自己看一遍地面', 1, 1, 3, 0, 0),
  ('kg-middle-bedtime-ready-1', 'kg-middle-bedtime-ready', '20:20', '20:30', 'sleep', '自己洗漱', 1, 0, 1, 0, 0),
  ('kg-middle-bedtime-ready-2', 'kg-middle-bedtime-ready', '20:30', '20:50', 'reading_interest', '睡前阅读', 1, 0, 2, 0, 0),
  ('kg-middle-bedtime-ready-3', 'kg-middle-bedtime-ready', '20:50', '21:00', 'sleep', '关灯躺好', 1, 0, 3, 0, 0),
  ('kg-middle-weekend-outdoor-1', 'kg-middle-weekend-outdoor', '09:30', '10:10', 'sports_outdoor', '户外跑跳', 2, 0, 1, 0, 0),
  ('kg-middle-weekend-outdoor-2', 'kg-middle-weekend-outdoor', '10:10', '10:20', 'life', '喝水擦汗', 1, 0, 2, 0, 0),
  ('kg-middle-weekend-outdoor-3', 'kg-middle-weekend-outdoor', '10:30', '10:45', 'reading_interest', '安静翻书', 1, 0, 3, 0, 0),
  ('kg-middle-family-helper-1', 'kg-middle-family-helper', '10:20', '10:30', 'housework', '摆好自己的餐具', 1, 0, 1, 0, 0),
  ('kg-middle-family-helper-2', 'kg-middle-family-helper', '10:30', '10:40', 'housework', '把纸巾放到桌上', 1, 0, 2, 0, 0),
  ('kg-middle-family-helper-3', 'kg-middle-family-helper', '10:40', '10:50', 'custom', '完成后告诉家人', 0, 0, 3, 0, 0),
  ('kg-middle-rules-turns-1', 'kg-middle-rules-turns', '15:30', '15:40', 'custom', '说好游戏规则', 0, 0, 1, 0, 0),
  ('kg-middle-rules-turns-2', 'kg-middle-rules-turns', '15:40', '16:10', 'sports_outdoor', '轮流玩一会儿', 2, 0, 2, 0, 0),
  ('kg-middle-rules-turns-3', 'kg-middle-rules-turns', '16:10', '16:20', 'custom', '说一句谢谢', 0, 0, 3, 0, 0),
  ('kg-middle-emotion-words-1', 'kg-middle-emotion-words', '19:30', '19:40', 'custom', '说说今天开心的事', 0, 0, 1, 0, 0),
  ('kg-middle-emotion-words-2', 'kg-middle-emotion-words', '19:40', '19:50', 'custom', '说说不舒服的事', 0, 0, 2, 0, 0),
  ('kg-middle-emotion-words-3', 'kg-middle-emotion-words', '19:50', '20:05', 'reading_interest', '读一本安静的书', 1, 0, 3, 0, 0),
  ('kg-middle-weekend-reading-1', 'kg-middle-weekend-reading', '15:20', '15:40', 'reading_interest', '亲子阅读', 1, 0, 1, 0, 0),
  ('kg-middle-weekend-reading-2', 'kg-middle-weekend-reading', '15:40', '15:50', 'custom', '说说喜欢的角色', 0, 0, 2, 0, 0),
  ('kg-middle-weekend-reading-3', 'kg-middle-weekend-reading', '15:50', '16:00', 'housework', '书放回原处', 1, 0, 3, 0, 0),
  ('kg-big-school-ready-1', 'kg-big-school-ready', '07:10', '07:25', 'life', '自己洗漱穿衣', 1, 0, 1, 0, 0),
  ('kg-big-school-ready-2', 'kg-big-school-ready', '07:30', '07:50', 'checkin', '专心吃早餐', 1, 0, 2, 0, 0),
  ('kg-big-school-ready-3', 'kg-big-school-ready', '07:55', '08:05', 'housework', '准备水杯和衣物', 1, 1, 3, 0, 0),
  ('kg-big-after-school-review-1', 'kg-big-after-school-review', '17:20', '17:35', 'custom', '分享今天一件事', 0, 0, 1, 0, 0),
  ('kg-big-after-school-review-2', 'kg-big-after-school-review', '17:40', '18:10', 'sports_outdoor', '户外活动', 2, 0, 2, 0, 0),
  ('kg-big-after-school-review-3', 'kg-big-after-school-review', '18:10', '18:20', 'life', '喝水休息', 1, 0, 3, 0, 0),
  ('kg-big-table-duty-1', 'kg-big-table-duty', '17:55', '18:05', 'housework', '摆好自己的餐具', 1, 0, 1, 0, 0),
  ('kg-big-table-duty-2', 'kg-big-table-duty', '18:05', '18:30', 'checkin', '专心吃饭', 1, 0, 2, 0, 0),
  ('kg-big-table-duty-3', 'kg-big-table-duty', '18:35', '18:45', 'housework', '餐后小整理', 1, 0, 3, 0, 0),
  ('kg-big-bedtime-self-1', 'kg-big-bedtime-self', '20:20', '20:30', 'sleep', '自己洗漱', 1, 0, 1, 0, 0),
  ('kg-big-bedtime-self-2', 'kg-big-bedtime-self', '20:30', '20:45', 'reading_interest', '睡前阅读', 1, 0, 2, 0, 0),
  ('kg-big-bedtime-self-3', 'kg-big-bedtime-self', '20:45', '21:00', 'sleep', '安静上床', 1, 0, 3, 0, 0),
  ('kg-big-weekend-outdoor-1', 'kg-big-weekend-outdoor', '09:30', '10:10', 'sports_outdoor', '户外活动', 2, 0, 1, 0, 0),
  ('kg-big-weekend-outdoor-2', 'kg-big-weekend-outdoor', '10:10', '10:20', 'life', '喝水休息', 1, 0, 2, 0, 0),
  ('kg-big-weekend-outdoor-3', 'kg-big-weekend-outdoor', '10:20', '10:35', 'housework', '整理外出物品', 1, 1, 3, 0, 0),
  ('kg-big-weekend-reading-1', 'kg-big-weekend-reading', '15:20', '15:40', 'reading_interest', '亲子阅读', 1, 0, 1, 0, 0),
  ('kg-big-weekend-reading-2', 'kg-big-weekend-reading', '15:40', '15:50', 'custom', '复述一个画面', 0, 0, 2, 0, 0),
  ('kg-big-weekend-reading-3', 'kg-big-weekend-reading', '15:50', '16:00', 'housework', '书放回原处', 1, 0, 3, 0, 0),
  ('kg-big-family-helper-1', 'kg-big-family-helper', '10:20', '10:30', 'housework', '摆好餐具', 1, 0, 1, 0, 0),
  ('kg-big-family-helper-2', 'kg-big-family-helper', '10:30', '10:40', 'housework', '帮忙分纸巾', 1, 0, 2, 0, 0),
  ('kg-big-family-helper-3', 'kg-big-family-helper', '10:40', '10:50', 'custom', '完成后说一声', 0, 0, 3, 0, 0),
  ('kg-big-own-things-1', 'kg-big-own-things', '16:00', '16:10', 'housework', '收好自己的衣物', 1, 1, 1, 0, 0),
  ('kg-big-own-things-2', 'kg-big-own-things', '16:10', '16:20', 'housework', '整理图书和玩具', 1, 0, 2, 0, 0),
  ('kg-big-own-things-3', 'kg-big-own-things', '16:20', '16:30', 'custom', '选一件明天要用的东西', 0, 0, 3, 0, 0),
  ('kg-big-life-prep-1', 'kg-big-life-prep', '19:40', '19:50', 'housework', '准备明天衣物', 1, 1, 1, 0, 0),
  ('kg-big-life-prep-2', 'kg-big-life-prep', '19:50', '20:00', 'life', '自己整理水杯', 1, 1, 2, 0, 0),
  ('kg-big-life-prep-3', 'kg-big-life-prep', '20:00', '20:10', 'custom', '说说明天计划', 0, 0, 3, 0, 0),
  ('kg-big-safety-rules-1', 'kg-big-safety-rules', '10:00', '10:10', 'custom', '说说外出规则', 0, 0, 1, 0, 0),
  ('kg-big-safety-rules-2', 'kg-big-safety-rules', '10:10', '10:45', 'sports_outdoor', '户外活动', 2, 0, 2, 0, 0),
  ('kg-big-safety-rules-3', 'kg-big-safety-rules', '10:45', '10:55', 'custom', '回顾一条规则', 0, 0, 3, 0, 0)
ON DUPLICATE KEY UPDATE
  template_id = VALUES(template_id),
  start_time = VALUES(start_time),
  end_time = VALUES(end_time),
  task_type = VALUES(task_type),
  title = VALUES(title),
  reward_points = VALUES(reward_points),
  requires_parent_confirmation = VALUES(requires_parent_confirmation),
  sort_order = VALUES(sort_order),
  updated_at = VALUES(updated_at);
