CREATE TABLE IF NOT EXISTS student_pairing_challenges (
  id VARCHAR(128) PRIMARY KEY,
  challenge_hash CHAR(64) NOT NULL,
  verifier_hash CHAR(64) NOT NULL,
  display_code CHAR(4) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'pending',
  device_label VARCHAR(255) NOT NULL,
  device_type VARCHAR(64) NOT NULL,
  device_model VARCHAR(255),
  device_hardware VARCHAR(255),
  platform VARCHAR(64) NOT NULL,
  os_version VARCHAR(64),
  browser_name VARCHAR(64),
  os_name VARCHAR(64),
  app_version VARCHAR(64),
  client_fingerprint_hash CHAR(64) NOT NULL,
  request_ip_hash CHAR(64),
  family_id VARCHAR(128),
  child_id VARCHAR(128),
  approved_by_user_id VARCHAR(128),
  rejected_by_user_id VARCHAR(128),
  pin_hash CHAR(64),
  pin_salt VARCHAR(64),
  pin_iterations INTEGER,
  expires_at BIGINT NOT NULL,
  approved_expires_at BIGINT,
  approved_at BIGINT,
  consumed_at BIGINT,
  rejected_at BIGINT,
  created_at BIGINT NOT NULL,
  updated_at BIGINT NOT NULL,
  UNIQUE KEY uq_student_pairing_challenges_hash(challenge_hash),
  INDEX idx_student_pairing_challenges_status(status, expires_at),
  INDEX idx_student_pairing_challenges_fingerprint(client_fingerprint_hash, created_at),
  INDEX idx_student_pairing_challenges_ip(request_ip_hash, created_at),
  INDEX idx_student_pairing_challenges_family(family_id, child_id, created_at)
);

CREATE TABLE IF NOT EXISTS student_pairing_challenge_rate_buckets (
  bucket_kind VARCHAR(16) NOT NULL,
  bucket_hash CHAR(64) NOT NULL,
  created_at BIGINT NOT NULL,
  updated_at BIGINT NOT NULL,
  PRIMARY KEY(bucket_kind, bucket_hash),
  INDEX idx_student_pairing_challenge_rate_buckets_updated(updated_at)
);
